name: build_and_test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
        lcov \
        libboost-dev \
        libeigen3-dev \
        libfmt-dev \
        libgtest-dev \
        ninja-build

    - name: Install autodiff
      run: |
        git clone --branch v1.0.3 https://github.com/autodiff/autodiff.git ${{ github.workspace }}/deps/autodiff
        cmake                                                  \
          -S ${{ github.workspace }}/deps/autodiff             \
          -B ${{ github.workspace }}/deps/autodiff/build       \
          -DAUTODIFF_BUILD_EXAMPLES=OFF                        \
          -DAUTODIFF_BUILD_TESTS=OFF                           \
          -DAUTODIFF_BUILD_PYTHON=OFF
        cmake --build ${{ github.workspace }}/deps/autodiff/build
        sudo cmake --install ${{ github.workspace }}/deps/autodiff/build

    - name: Run cmake workflow
      working-directory: ${{ github.workspace }}
      run: cmake --workflow --preset ci

    - name: Analyze coverage
      working-directory: ${{ github.workspace }}
      run: |
        lcov -c --no-external --directory include -d build/tests/CMakeFiles -o coverage.info
        lcov --list coverage.info
        bash <(curl -s https://codecov.io/bash) -f coverage.info -t ${{ secrets.CODECOV_TOKEN }}
